/* eslint-disable react/jsx-no-undef */
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Socket.io Demo",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${inter.className} bg-zinc-50`}>
                {children}
                <Toaster position="top-right" reverseOrder={false} />
            </body>
        </html>
    );
}